git:
  depth: 2000

language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode6.2
      compiler: clang
      sudo: required

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install qt openssl miniupnpc libmicrohttpd sqlcipher xapian; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew link --force qt ; fi

  - wget https://github.com/Tencent/rapidjson/archive/v1.1.0.tar.gz
  - tar -xf v1.1.0.tar.gz
  - if [ $TRAVIS_OS_NAME == osx ]; then cp -r rapidjson-1.1.0/include/rapidjson/ /usr/local/include/rapidjson ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ln -s /usr/local/opt/openssl/include/* /usr/local/include/; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ln -s /usr/local/opt/openssl/lib/*.a /usr/local/lib/; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ln -s /usr/local/opt/openssl/lib/*.dylib /usr/local/lib/; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GvA+CSM1ksvsmnkFkyWmQYcvFIJqd/fJVFGUcv/wBlrAqAWka1YRph8ox7L3+tJyISrf0MW7v+W7Rm7FOOMleeP+n4aWtFBr41R22RzlgMt6coRqho7qrNud6JkPk/Iuw2dtyMyfrTb+H+alPHs+SUnQxQ/i9Px8W7V94LTG6cim5zksNFkD7RPI94dFT/84teOEet+2NqHHuAZsf7Xfs7rk3triWPkcr7x9fzgGw/QvvKOmJwrprjmi1iKX/+cnu8adGwrmR7Q5bEvFkyChOVfiXymQQVOL4nD17PfT3fOA6u/w1pWD9jw0EsDpXP5dL8HZ6EDUoMKsUtTe2vlH40Ls+E8CA011y1VuXgRVzOzYk/TPecrW4aAmPPJJKiWnvg+URTf+A9YyphUVxwaaYXWcHWYO+zFF9N4YrOsgQAdQ+M6dg19nSPn/53VhoD4PFxS65ajBEgZi6WTwyk/AChmRXklqNHD0GOSKYW3M15BoAGh7tCrUkIhhEGmaoUsmJzA5od9H5+QxkSSS4suZFu9j8KJIthfukyF+Y1n3zDsqBS4XVYMIMno4+Jd65Qy4MQC7yPanHcpV6FOyfs7s3aXE4yUa+66iIRAr9LJDu41iLpMKUxADrAbhZwxm9vzBbQxqpJHwH6Rv9C+T5zqNuldmaRBtei05sOtD3AlJWaE="

addons:
  coverity_scan:
    project:
      name: "RetroShare/RetroShare"
      description: "RetroShare Build submitted via Travis CI"
    build_command_prepend: "qmake CONFIG+=no_sqlcipher; make clean"
    build_command: "make -j4"
    branch_pattern: coverity_scan

before_script:
  - if [ $TRAVIS_OS_NAME == osx ]; then qmake QMAKE_CC=$CC QMAKE_CXX=$CXX CONFIG+=rs_macos10.12 CONFIG+=no_retroshare_plugins INCLUDEPATH+=/usr/local/opt/openssl/include/ QMAKE_LIBDIR+=/usr/local/opt/openssl/lib/; fi

script:
  - if [ $TRAVIS_OS_NAME == osx ] && [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make -j4; fi
after_success:
  - if [ $TRAVIS_OS_NAME == osx ]; then chmod +x ./travis_makeOSXPackage.sh && ./travis_makeOSXPackage.sh ; fi

branches:
  only:
  - v0.6-MacOS-Travis-Deploy

deploy:
  provider: releases
  api_key:
    secure: GvA+CSM1ksvsmnkFkyWmQYcvFIJqd/fJVFGUcv/wBlrAqAWka1YRph8ox7L3+tJyISrf0MW7v+W7Rm7FOOMleeP+n4aWtFBr41R22RzlgMt6coRqho7qrNud6JkPk/Iuw2dtyMyfrTb+H+alPHs+SUnQxQ/i9Px8W7V94LTG6cim5zksNFkD7RPI94dFT/84teOEet+2NqHHuAZsf7Xfs7rk3triWPkcr7x9fzgGw/QvvKOmJwrprjmi1iKX/+cnu8adGwrmR7Q5bEvFkyChOVfiXymQQVOL4nD17PfT3fOA6u/w1pWD9jw0EsDpXP5dL8HZ6EDUoMKsUtTe2vlH40Ls+E8CA011y1VuXgRVzOzYk/TPecrW4aAmPPJJKiWnvg+URTf+A9YyphUVxwaaYXWcHWYO+zFF9N4YrOsgQAdQ+M6dg19nSPn/53VhoD4PFxS65ajBEgZi6WTwyk/AChmRXklqNHD0GOSKYW3M15BoAGh7tCrUkIhhEGmaoUsmJzA5od9H5+QxkSSS4suZFu9j8KJIthfukyF+Y1n3zDsqBS4XVYMIMno4+Jd65Qy4MQC7yPanHcpV6FOyfs7s3aXE4yUa+66iIRAr9LJDu41iLpMKUxADrAbhZwxm9vzBbQxqpJHwH6Rv9C+T5zqNuldmaRBtei05sOtD3AlJWaE=
  file: retroshare-gui/src/retroshare.dmg
  skip_cleanup: true
  on:
    repo: csoler/RetroShare
    branch: v0.6-MacOS-Travis-Deploy

