language: cpp
matrix:
  include:
#  - os: linux
#    dist: trusty
#    sudo: required
#    compiler: gcc
  - os: osx
    osx_image: xcode6.2
    compiler: clang
    sudo: required
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y build-essential checkinstall
  cmake libavutil-dev libavcodec-dev libavformat-dev libbz2-dev libcurl4-openssl-dev
  libcv-dev libopencv-highgui-dev libhighgui-dev libgnome-keyring-dev libgstreamer-plugins-base0.10-dev
  libgstreamer0.10-dev libjasper-dev libjpeg-dev libmicrohttpd-dev libopencv-dev libprotobuf-dev
  libqt4-dev libspeex-dev libspeexdsp-dev libsqlite3-dev libssl-dev libswscale-dev
  libtbb-dev libtiff4-dev libupnp-dev libv4l-dev libxine-dev libxslt1-dev libxss-dev
  pkg-config protobuf-compiler python-dev qtmobility-dev gdb ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew install qt55 openssl miniupnpc libmicrohttpd
  speex speexdsp ffmpeg sqlcipher ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew link --force qt55 ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then rm '/usr/local/bin/f2py'; fi
- if [ $TRAVIS_OS_NAME == osx ]; then rm -r '/usr/local/lib/python2.7/site-packages/numpy';
  fi
#- if [ $TRAVIS_OS_NAME == osx ]; then brew install homebrew/science/opencv; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ln -s /usr/local/opt/openssl/include/* /usr/local/include/;
  fi
- if [ $TRAVIS_OS_NAME == osx ]; then ln -s /usr/local/opt/openssl/lib/*.a /usr/local/lib/;
  fi
- if [ $TRAVIS_OS_NAME == osx ]; then ln -s /usr/local/opt/openssl/lib/*.dylib /usr/local/lib/;
  fi
before_script:
# no_sqlcipher removed from build command. Apparently MacOS can handle it. To be tested.
- chmod +x ./travis_setupVersionNumber.sh && ./travis_setupVersionNumber.sh
- qmake QMAKE_CC=$CC QMAKE_CXX=$CXX CONFIG+="no_retroshare_plugins" CONFIG+=tests
script:
- if [ $TRAVIS_OS_NAME == linux ] ; then make && tests/unittests/unittests >/dev/null
  2>&1 ; fi
- if [ $TRAVIS_OS_NAME == osx ] ; then make -j 4 ; fi
after_success:
- if [ $TRAVIS_OS_NAME == osx ]; then chmod +x ./travis_makeOSXPackage.sh && ./travis_makeOSXPackage.sh
  ; fi
branches:
  only:
  - v0.6.3-TravisDeploy
deploy:
  provider: releases
  api_key:
    secure: GvA+CSM1ksvsmnkFkyWmQYcvFIJqd/fJVFGUcv/wBlrAqAWka1YRph8ox7L3+tJyISrf0MW7v+W7Rm7FOOMleeP+n4aWtFBr41R22RzlgMt6coRqho7qrNud6JkPk/Iuw2dtyMyfrTb+H+alPHs+SUnQxQ/i9Px8W7V94LTG6cim5zksNFkD7RPI94dFT/84teOEet+2NqHHuAZsf7Xfs7rk3triWPkcr7x9fzgGw/QvvKOmJwrprjmi1iKX/+cnu8adGwrmR7Q5bEvFkyChOVfiXymQQVOL4nD17PfT3fOA6u/w1pWD9jw0EsDpXP5dL8HZ6EDUoMKsUtTe2vlH40Ls+E8CA011y1VuXgRVzOzYk/TPecrW4aAmPPJJKiWnvg+URTf+A9YyphUVxwaaYXWcHWYO+zFF9N4YrOsgQAdQ+M6dg19nSPn/53VhoD4PFxS65ajBEgZi6WTwyk/AChmRXklqNHD0GOSKYW3M15BoAGh7tCrUkIhhEGmaoUsmJzA5od9H5+QxkSSS4suZFu9j8KJIthfukyF+Y1n3zDsqBS4XVYMIMno4+Jd65Qy4MQC7yPanHcpV6FOyfs7s3aXE4yUa+66iIRAr9LJDu41iLpMKUxADrAbhZwxm9vzBbQxqpJHwH6Rv9C+T5zqNuldmaRBtei05sOtD3AlJWaE=
  file: retroshare-gui/src/retroshare.dmg
  skip_cleanup: true
  on:
    repo: csoler/RetroShare
    branch: v0.6.3-TravisDeploy

